services:
  backend:
    build: ./bezo-backend
    ports:
      - "3000:3000"
    env_file:
      - ./bezo-backend/.env
    restart: always

  frontend:
    build: ./Bezo
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
